casadocodigo/src/main/java/br/com/casadocodigo/loja/models/CarrinhoCompras.java
package br.com.casadocodigo.loja.models;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

@Component
@Scope(value = WebApplicationContext.SCOPE_SESSION)
public class CarrinhoCompras implements Serializable{

	private static final long serialVersionUID = 1L;

	private Map<CarrinhoItem, Integer> itens = new LinkedHashMap<CarrinhoItem, Integer>();
	
	public void add(CarrinhoItem item) {
		itens.put(item, getQuantidade(item) + 1);
	}

	public Collection<CarrinhoItem> getItens(){
		return itens.keySet();
	}

	public int getQuantidade(CarrinhoItem item) {
		if(!itens.containsKey(item)) {
			itens.put(item, 0);
		}
		return itens.get(item);
	}
	
	public int getQuantidade() {
		return itens.values().stream().reduce(0, (proximo, acumulador) -> proximo + acumulador);
	}
	
	public BigDecimal getTotal(CarrinhoItem item) {
		return item.getTotal(getQuantidade(item));
	}

	public BigDecimal getTotal() {
		BigDecimal total = BigDecimal.ZERO;
		for (CarrinhoItem item : itens.keySet()) {
			total = total.add(getTotal(item));
		}
		return total;
	}

	public void remover(Integer produtoId, TipoPreco tipoPreco) {
		Produto produto = new Produto();
		produto.setId(produtoId);
		itens.remove(new CarrinhoItem(produto, tipoPreco));
		
	}
}

casadocodigo/src/main/java/br/com/casadocodigo/loja/controller/HomeController.java
package br.com.casadocodigo.loja.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import br.com.casadocodigo.loja.dao.ProdutoDAO;
import br.com.casadocodigo.loja.models.Produto;

@Controller
public class HomeController {
	
	@Autowired
	private ProdutoDAO produtoDAO;
	
	@RequestMapping("/")
	@Cacheable("produtosHome")
	public ModelAndView index() {
		List<Produto> produtos = produtoDAO.buscar();
		ModelAndView modelAndView = new ModelAndView("home");
		modelAndView.addObject("produto", produtos);
		return modelAndView;
	}
	
	
}

casadocodigo/src/main/java/br/com/casadocodigo/loja/controller/LoginController.java
package br.com.casadocodigo.loja.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class LoginController {
	
	@RequestMapping(value="/login", method=RequestMethod.GET)
	public String loginForm() {
		return "loginForm";
	}
}

casadocodigo/src/main/webapp/WEB-INF/views/cabecalho.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
  <header id="layout-header">
		<div class="clearfix container">
			<a href="${s:mvcUrl('HC#index').build() }" id="logo">
			</a>
			<div id="header-content">
				<nav id="main-nav">
					
					<ul class="clearfix">
						<li><a href="${s:mvcUrl('CCC#itens').build() }" rel="nofollow">
							<s:message code="menu.carrinho" arguments="${carrinhoCompras.quantidade }"/>
						</a></li>

						<li><a href="/pages/sobre-a-casa-do-codigo" rel="nofollow">
							<fmt:message key="menu.sobre"/>
						</a></li>
						
						<li><a href="?Locale=pt" rel="nofollow">
							<fmt:message key="menu.pt"/>
						</a></li>
						<li><a href="?Locale=en_US" rel="nofollow">
							<fmt:message key="menu.en"/>
						</a></li>

						<li><a href="/pages/perguntas-frequentes" rel="nofollow">Perguntas Frequentes</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<nav class="categories-nav">
		<ul class="container">
			<li class="category"><a href="http://www.casadocodigo.com.br"><fmt:message key="navegacao.categoria.home"/></a></li>
			<li class="category"><a href="/collections/livros-de-agile">
					<fmt:message key="navegacao.categoria.agile"/> </a></li>
			<li class="category"><a href="/collections/livros-de-front-end">
					<fmt:message key="navegacao.categoria.front_end"/> </a></li>
			<li class="category"><a href="/collections/livros-de-games">
					<fmt:message key="navegacao.categoria.games"/> </a></li>
			<li class="category"><a href="/collections/livros-de-java">
					<fmt:message key="navegacao.categoria.java"/> </a></li>
			<li class="category"><a href="/collections/livros-de-mobile">
					<fmt:message key="navegacao.categoria.mobile"/> </a></li>
			<li class="category"><a
				href="/collections/livros-desenvolvimento-web"> <fmt:message key="navegacao.categoria.web"/> </a></li>
			<li class="category"><a href="/collections/outros"> <fmt:message key="navegacao.categoria.outros"/> </a></li>
		</ul>
	</nav>

casadocodigo/src/main/webapp/WEB-INF/views/error.jsp
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<tags:pageTemplate titulo="Produto não encontrado">
		
	<section id="index-section" class="container middle">
		<h2>Erro generico acontecendo</h2>
		
		<!-- 
			mensagem: ${exception.message }
			<c:forEach items="${exception.stackTrace }" var="stk">
				${stk }
			</c:forEach>
			
		 -->
	</section>
</tags:pageTemplate>

casadocodigo/src/main/webapp/WEB-INF/views/loginForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Livros de Java, Android, Iphone, Ruby, PHP e muito mais -
	Casa do código</title>
<c:url value="/resources/css" var="cssPath" />
<link rel="stylesheet" href="${cssPath }/bootstrap.min.css">
<link rel="stylesheet" href="${cssPath }/css/bootstrap-theme.min.css">
<script src="${cssPath }/css/bootstrap.min.css/js/bootstrap.min.js"></script>
<style type="text/css">
.body {
	padding: 60px
}
</style>

</head>
<body>
	<div class="container">
		<h1>Login da Casa do código</h1>

		<form:form servletRelativeAction="/login" method="post">
			<div class="form-group">
				<label>E-mail</label> <input name="username" type="text"
					class="form-control" />
			</div>
			<div class="form-group">
				<label>Senha</label> <input name="password" type="password"
					class="form-control" />
			</div>

			<button type="submit" class="btn btn-primary">Logar</button>
		</form:form>
	</div>
</body>
</html>